name: e2e-tests
on: [push]
jobs:
  cypress-run:
    runs-on:  windows-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1,2,3]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{'secrets.CYPRESS_RECORD_KEY'}}